# Generated by Django 4.1.4 on 2022-12-09 00:23

from django.conf import settings
from django.db import migrations, models
import post.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=post.models.getImageUrl)),
                ('like_number', models.IntegerField(default=0)),
                ('comment_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.ManyToManyField(related_name='user_comment', to=settings.AUTH_USER_MODEL)),
                ('likers', models.ManyToManyField(related_name='user_liker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
