# Generated by Django 4.1.4 on 2022-12-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_comments_options_comments_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post_id',
        ),
    ]
